### ISSUE TITLE
Wrong home URL in os-release

### ISSUE THREAD

**Issue by sparkiegeek** [snapcore/base-18#13]
https://github.com/snapcore/base-18/blob/1a3c99f5d5e5c6f266dfcb914602d23225e8d802/hooks/18-set-os-release.chroot#L9

This should be https://snapcraft.io (HTTP/S and no www)

**Comment by zyga** [comment]
I will fix this in a moment, just working on spread test support.

**Comment by sparkiegeek** [comment]
Ah, added the PR before noticing your reply here, do with it as you wish!
